name: CI DEMO

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# runs-on: ubuntu-latest
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: hello-world
            - run: echo "hello world" 


