name: CI DEMO

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

# runs-on: ubuntu-latest
jobs:
    hello:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Print hello world
          run: echo "hello world"


